// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvaefyxptjnflbfviwre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2YWVmeXhwdGpuZmxiZnZpd3JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4Nzc0NDgsImV4cCI6MjA2MDQ1MzQ0OH0.qzz3_e8RDhsnI8ayk9e1r8qEOIrIouc5AhqQWL2Xs5I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);